ALTER TABLE Groups ADD COLUMN leader TEXT;
ALTER TABLE Groups ADD COLUMN image TEXT;
ALTER TABLE Groups ADD COLUMN history TEXT;
ALTER TABLE Groups ADD COLUMN isShow INTEGER;
ALTER TABLE Groups ADD COLUMN lastUpdate INTEGER;
DELETE FROM Groups;